- hosts: localhost
  tasks:
    - name: Install Packages
      become: yes
      dnf:
          name: ['xorg-x11-drv-amdgpu','keepassxc','grub-customizer','vlc','wine','telegram-desktop','vim','libreoffice','neofetch','winetricks','kvantum','cmake','extra-cmake-modules','fftw3','fftw-devel','steam','git','qbittorrent','mesa-libGLU.i686','redshift','lm_sensors','htop','audacity','ffmpeg','krita','rclone','@virtualization','kate','qmmp','qmmp-plugin-pack-freeworld','lutris','rcm','xdg-desktop-portal-kde']
          state: present
    - name: Remove unneeded packages
      become: yes
      dnf: 
          name: ['plasma-discover','amarok','kdepim','kdepim-runtime','kdepim-apps-libs','calligra-core','kamoso','dragonplayer','juk','packagekit','krusader','konqueror','falkon','konversation','ktorrent','kget','kmail']
          state: absent
